language: python

python: 2.7

env:
- TOXENV=py26
- TOXENV=py27
- TOXENV=py34
- TOXENV=cov
- TOXENV=pylint
- TOXENV=pep8

branches:
  only:
  - master
  - develop

install: pip install --quiet tox

script: tox

after_script:
- if [ $TOXENV == "cov" ]; then
    pip install --quiet coveralls;
    coveralls;
  fi
